POST http://localhost:3000/api/user
Accept: application/json
Content-Type: application/json

{
  "username": "calle",
  "password": "demo",
  "email": "calle@demo.com",
  "user": "callcenter"
}

###
PUT http://localhost:3000/api/user/61a062df92e892f85b652f8f
Accept: application/json
Content-Type: application/json

{
  "localgovt": "LAGOS ISLAND",
  "state": "LAGOS",
  "ward": "OLOSUN"
}

###
GET http://localhost:3000/api/user/61a062df92e892f85b652f8f

###
GET http://localhost:3000/api/user

###
POST https://pdpereg.vercel.app/api/user
Accept: application/json
Content-Type: application/json

{
  "username": "agent",
  "password": "demo",
  "email": "agent@demo.com",
  "usertype": "agent"
}

###
PUT https://pdpereg.vercel.app/api/user/61a07b604b82161f83b51932
Accept: application/json
Content-Type: application/json

{
  "usertype": "callcenter"
}
